Fixed deluge script to pull config from the right place.

diff --git a/deluge/deluge_init_d_script b/deluge/deluge_init_d_script
--- a/deluge/deluge_init_d_script
+++ b/deluge/deluge_init_d_script
@@ -1,104 +1,65 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          deluge-daemon
+# Provides:          deluged
 # Required-Start:    $local_fs $remote_fs
 # Required-Stop:     $local_fs $remote_fs
 # Should-Start:      $network
 # Should-Stop:       $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Daemonized version of deluge and webui.
-# Description:       Starts the deluge daemon with the user specified in
-#                    /etc/default/deluge-daemon.
+# Short-Description: Start or stop the Deluge BitTorrent daemon.
+# Description:       Start or stop the Deluge BitTorrent daemon.
 ### END INIT INFO
 
-# Author: Adolfo R. Brandes 
-# Updated by: Jean-Philippe "Orax" Roemer
+# Authors: Tanguy Ortolo <tanguy+debian@ortolo.eu>,
+# Cristian Greco <cristian@regolo.cc>
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DESC="Deluge Daemon"
-NAME1="deluged"
-NAME2="deluge"
-DAEMON1=/usr/bin/deluged
-DAEMON1_ARGS="-d -L warning -l /var/log/deluge/daemon/warning.log"             # Consult `man deluged` for more options
-DAEMON2=/usr/bin/deluge-web
-DAEMON2_ARGS="-L warning -l /var/log/deluge/web/warning.log"               # Consult `man deluge-web` for more options
-PIDFILE1=/var/run/$NAME1.pid
-PIDFILE2=/var/run/$NAME2.pid
-UMASK=022                     # Change this to 0 if running deluged as its own user
-PKGNAME=deluge-daemon
-SCRIPTNAME=/etc/init.d/$PKGNAME
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Deluge BitTorrent Daemon"
+NAME="deluged"
+DAEMON=/usr/bin/$NAME
+DAEMON_ARGS="-d -c /home/bsmith/.config/deluge/ -L warning -l /var/log/deluged/daemon.log"
+USER=debian-deluged
+MASK=0027
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
-[ -x "$DAEMON1" -a -x "$DAEMON2" ] || exit 0
+[ -x "$DAEMON" ] || exit 0
+
+ENABLE_DELUGED=1
 
 # Read configuration variable file if it is present
-[ -r /etc/default/$PKGNAME ] && . /etc/default/$PKGNAME
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 # Load the VERBOSE setting and other rcS variables
 [ -f /etc/default/rcS ] && . /etc/default/rcS
 
 # Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
-
-if [ -z "$RUN_AT_STARTUP" -o "$RUN_AT_STARTUP" != "YES" ]
-then
-   log_warning_msg "Not starting $PKGNAME, edit /etc/default/$PKGNAME to start it."
-   exit 0
-fi
-
-if [ -z "$DELUGED_USER" ]
-then
-    log_warning_msg "Not starting $PKGNAME, DELUGED_USER not set in /etc/default/$PKGNAME."
-    exit 0
-fi
-
-#
-# Function to verify if a pid is alive
-#
-is_alive()
-{
-   pid=`cat $1` > /dev/null 2>&1
-   kill -0 $pid > /dev/null 2>&1
-   return $?
-}
 
 #
 # Function that starts the daemon/service
 #
 do_start()
 {
-   # Return
-   #   0 if daemon has been started
-   #   1 if daemon was already running
-   #   2 if daemon could not be started
+  if [ $ENABLE_DELUGED != 1 ]; then
+    log_progress_msg "Not starting ${DESC} ${NAME}, disabled in /etc/default/${NAME}"
+  else
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec $DAEMON \
+      --chuid $USER --umask $MASK --test > /dev/null \
+      || return 1
 
-   is_alive $PIDFILE1
-   RETVAL1="$?"
-
-   if [ $RETVAL1 != 0 ]; then
-       rm -f $PIDFILE1
-       start-stop-daemon --start --background --quiet --pidfile $PIDFILE1 --make-pidfile \
-       --exec $DAEMON1 --chuid $DELUGED_USER --user $DELUGED_USER --umask $UMASK -- $DAEMON1_ARGS
-       RETVAL1="$?"
-   else
-       is_alive $PIDFILE2
-       RETVAL2="$?"
-       [ "$RETVAL2" = "0" -a "$RETVAL1" = "0" ] && return 1
-   fi
-
-   is_alive $PIDFILE2
-   RETVAL2="$?"
-
-   if [ $RETVAL2 != 0 ]; then
-        sleep 2
-        rm -f $PIDFILE2
-        start-stop-daemon --start --background --quiet --pidfile $PIDFILE2 --make-pidfile \
-        --exec $DAEMON2 --chuid $DELUGED_USER --user $DELUGED_USER --umask $UMASK -- $DAEMON2_ARGS
-        RETVAL2="$?"
-   fi
-   [ "$RETVAL1" = "0" -a "$RETVAL2" = "0" ] || return 2
+    start-stop-daemon --start --background --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON \
+      --chuid $USER --umask $MASK -- $DAEMON_ARGS \
+      || return 2
+  fi
 }
 
 #
@@ -106,62 +67,62 @@ do_start()
 #
 do_stop()
 {
-   # Return
-   #   0 if daemon has been stopped
-   #   1 if daemon was already stopped
-   #   2 if daemon could not be stopped
-   #   other if a failure occurred
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
 
-   start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --user $DELUGED_USER --pidfile $PIDFILE2
-   RETVAL2="$?"
-   start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --user $DELUGED_USER --pidfile $PIDFILE1
-   RETVAL1="$?"
-   [ "$RETVAL1" = "2" -o "$RETVAL2" = "2" ] && return 2
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+  RETVAL="$?"
+  [ "$RETVAL" = "2" ] && return 2
 
-   rm -f $PIDFILE1 $PIDFILE2
-
-   [ "$RETVAL1" = "0" -a "$RETVAL2" = "0" ] && return 0 || return 1
+  rm -f $PIDFILE
+  return "$RETVAL"
 }
 
 case "$1" in
   start)
-   [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME1"
-   do_start
-   case "$?" in
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
       0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
       2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-   esac
-   ;;
+    esac
+    ;;
   stop)
-   [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME1"
-   do_stop
-   case "$?" in
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
       0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
       2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-   esac
-   ;;
+    esac
+    ;;
+  status)
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
   restart|force-reload)
-   log_daemon_msg "Restarting $DESC" "$NAME1"
-   do_stop
-   case "$?" in
-     0|1)
-      do_start
-      case "$?" in
-         0) log_end_msg 0 ;;
-         1) log_end_msg 1 ;; # Old process is still running
-         *) log_end_msg 1 ;; # Failed to start
-      esac
-      ;;
-     *)
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1 ;; # Old process is still running
+          *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
         # Failed to stop
-      log_end_msg 1
-      ;;
-   esac
-   ;;
+        log_end_msg 1
+        ;;
+    esac
+    ;;
   *)
-   echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
-   exit 3
-   ;;
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
 
 :
